### ISSUE TITLE
Vapor 2.0 Support

### ISSUE THREAD

**Issue by Antonasg** [calebkleveter/UIWebKit#9]
It fails when trying to build with Vapor 2.0

It seems like it is changes to `Node` that makes it fail, but I'll have to look into it further.

**Comment by calebkleveter** [comment]
I will be looking into porting this over today.

**Comment by calebkleveter** [comment]
If you have any specific errors you can share, that would be great.

**Comment by calebkleveter** [comment]
Just pushed the fixes.
